clear all
close all
sca
pic1 = imread('C:\Users\arsenal\Documents\MATLAB\pic1.png')
pic2 = imread('C:\Users\arsenal\Documents\MATLAB\pic2.png')
pic3 = imread('C:\Users\arsenal\Documents\MATLAB\pic3.png')
pic4 = imread('C:\Users\arsenal\Documents\MATLAB\pic4.png')
pic5 = imread('C:\Users\arsenal\Documents\MATLAB\pic5.png')
pic6 = imread('C:\Users\arsenal\Documents\MATLAB\pic6.png')
pic7 = imread('C:\Users\arsenal\Documents\MATLAB\pic7.png')
pic8 = imread('C:\Users\arsenal\Documents\MATLAB\pic8.png')
Screen('Preference','SkipSyncTests',1)
[wp, rect]= Screen('OpenWindow',0)   
pauseduration=0.1
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
for i=1:10
Screen('PutImage',wp,pic1)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
Screen('PutImage',wp,pic2)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
Screen('PutImage',wp,pic3)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
Screen('PutImage',wp,pic4)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
Screen('PutImage',wp,pic5)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
Screen('PutImage',wp,pic6)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
Screen('PutImage',wp,pic7)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
Screen('PutImage',wp,pic8)
DrawFormattedText (wp,'BETA MOVEMENT','center',50)
Screen('Flip',wp)
pause(pauseduration)
end
pause(3)
Screen ('CloseAll')

